pragma Singleton

import Quickshell

Singleton {
    readonly property string authSystem: "Wymagane uwierzytelnienie"
    readonly property string authSsh: "Uwierzytelnianie SSH"
    readonly property string authTouch: "Dotknij klucza bezpieczeństwa"
    readonly property string authTouchHint: "SSH czeka na potwierdzenie na kluczu."
    readonly property string authSecret: "Hasło lub PIN"
    readonly property string authPassword: "Hasło"
    readonly property string authUnlockIn: "(Odblokowanie za %1 min)"
    readonly property string workspaceSwitcher: "Workspaces"
    readonly property string workspace: "Workspace"
    readonly property string workspaceSwitcherHint: "Super + Tab · 1–9 / 0"
    readonly property string noOccupiedWorkspaces: "Brak zajętych workspace’ów"
    readonly property string caffeinate: "Caffeinate"
    readonly property string caffeinateReason: "Caffeinate: komputer ma pozostać aktywny"
    readonly property string caffeinateFailed: "Nie udało się włączyć Caffeinate."
    readonly property string caffeinateBackground: "Praca w tle"
    readonly property string caffeinateBackgroundHint: "Komputer pracuje. Ekran gaśnie, bez blokady."
    readonly property string caffeinatePresentation: "Prezentacja"
    readonly property string caffeinatePresentationHint: "Komputer i ekran aktywne, bez blokady."
    readonly property string caffeinateSecureBackground: "Bezpieczna praca w tle"
    readonly property string caffeinateSecureBackgroundShort: "Bezpieczne tło"
    readonly property string caffeinateSecureBackgroundHint: "Komputer pracuje. Ekran gaśnie i się blokuje."
    readonly property string caffeinateChooseMode: "Wybierz tryb Caffeinate"
    readonly property string caffeinateOff: "Wyłącz Caffeinate"
    readonly property string quickSettings: "Szybkie menu"
    readonly property string screenshot: "Zrzut ekranu"
    readonly property string screenshotRegion: "Obszar"
    readonly property string screenshotWindow: "Okno"
    readonly property string screenshotMonitor: "Monitor"
    readonly property string screenshotCopy: "Kopiuj"
    readonly property string screenshotSave: "Zapisz"
    readonly property string screenshotEdit: "Edytuj"
    readonly property string screenshotEditorMissing: "Zainstaluj Satty, aby edytować zrzuty."
    readonly property string screenshotRegionHint: "Przeciągnij, aby zaznaczyć obszar"
    readonly property string screenshotWindowHint: "Wybierz okno"
    readonly property string screenshotWindowHoverHint: "Kliknij, aby wybrać"
    readonly property string screenshotMonitorHint: "Wybierz monitor"
    readonly property string screenshotNoWindows: "Brak dostępnych okien na tym monitorze"
    readonly property string screenshotKeyboardHint: "1–3 tryb · Tab wybór · Enter kopiuj · Esc anuluj"
    readonly property string screenshotSelectionHint: "Strzałki przesuń · Shift + strzałki zmień rozmiar"
    readonly property string screenshotWindowKeyboardHint: "← / → wybierz okno · Enter kopiuj"
    readonly property string screenshotMonitorKeyboardHint: "← / → wybierz monitor · Enter kopiuj"
    readonly property string screenshotWorking: "Przygotowywanie zrzutu…"
    readonly property string screenshotSelectedWindow: "Wybrane okno"
    readonly property string screenshotSelectedRegion: "Wybrany obszar"
    readonly property string screenshotUnavailable: "Przechwytywanie ekranu jest niedostępne."
    readonly property string screenshotCaptureFailed: "Nie udało się przechwycić obrazu. Spróbuj ponownie."
    readonly property string screenshotCaptureTimeout: "Przechwytywanie ekranu trwało zbyt długo."
    readonly property string screenshotScreenChanged: "Układ ekranów zmienił się. Wykonaj zrzut ponownie."
    readonly property string screenshotNoWindow: "Na tym ekranie nie ma okna do zaznaczenia."
    readonly property string screenshotExportFailed: "Nie udało się przygotować obrazu."
    readonly property string screenshotActionFailed: "Nie udało się ukończyć operacji."
    readonly property string screenshotLocked: "Zrzuty ekranu są niedostępne podczas blokady."
    readonly property string screenshotClipboardMissing: "Kopiowanie wymaga wl-copy."
    readonly property string screenshotSaveFailed: "Nie udało się zapisać zrzutu."
    readonly property string screenshotPrepareFailed: "Nie udało się przygotować katalogu tymczasowego."
    readonly property string screenshotSaved: "Zapisano zrzut ekranu"
    readonly property string screenshotSavedBody: "Kliknij, aby otworzyć zapisany obraz."
    readonly property string screenshotOpen: "Otwórz"
    readonly property string microphone: "Mikrofon"
    readonly property string volume: "Głośność"
    readonly property string audioDeviceHoldHint: "Spacja wycisza · Enter wybiera urządzenie · przytrzymanie ikony przez 1 s otwiera listę."
    readonly property string noAudioInputs: "Brak urządzeń wejściowych"
    readonly property string noAudioOutputs: "Brak urządzeń wyjściowych"
    readonly property string unavailable: "Usługa niedostępna"
    readonly property string loading: "Ładowanie…"
    readonly property string error: "Wystąpił błąd"
    readonly property string close: "Zamknij"
    readonly property string lockPassword: "Hasło"
    readonly property string lockPasswordFailed: "Nieprawidłowe hasło. Spróbuj ponownie."
    readonly property string lockFingerprint: "Odblokuj odciskiem palca"
    readonly property string lockFingerprintFailed: "Nie rozpoznano odcisku. Spróbuj ponownie."
    readonly property string lockAuthUnavailable: "Uwierzytelnianie niedostępne. Spróbuj ponownie."
    readonly property string cancel: "Anuluj"
    readonly property string confirm: "Potwierdź"
    readonly property string search: "Szukaj…"
    readonly property string noResults: "Brak wyników"
    readonly property string launcherRecent: "ostatnie"
    readonly property string launcherApplications: "aplikacje"
    readonly property string launcherFiles: "pliki"
    readonly property string launcherClipboard: "schowek"
    readonly property string launcherCommand: "komenda"
    readonly property string launcherCommandForeground: "Uruchom w terminalu na pierwszym planie"
    readonly property string launcherCommandBackground: "Uruchom w terminalu w tle"
    readonly property string launcherCommandHint: "Wpisz komendę · -q uruchamia w tle"
    readonly property string launcherRemoveFilter: "Usuń filtr"
    readonly property string launcherEmptyHistory: "Brak ostatnio uruchamianych rzeczy"
    readonly property string launcherHistoryUnavailable: "Historia jest dostępna tylko w tej sesji."
    readonly property string launcherSearchFailed: "Nie można wyszukać plików."
    readonly property string clipboard: "Schowek"
    readonly property string clearClipboard: "Wyczyścić całą historię schowka?"
    readonly property string clearClipboardAction: "Wyczyść schowek"
    readonly property string clear: "Wyczyść"
    readonly property string power: "Zasilanie"
    readonly property string lock: "Zablokuj"
    readonly property string suspend: "Uśpij"
    readonly property string hibernate: "Hibernuj"
    readonly property string logout: "Wyloguj"
    readonly property string reboot: "Uruchom ponownie"
    readonly property string poweroff: "Wyłącz"
    readonly property string wifi: "Wi‑Fi"
    readonly property string bluetooth: "Bluetooth"
    readonly property string audio: "Dźwięk"
    readonly property string brightness: "Jasność"
    readonly property string battery: "Bateria"
    readonly property string energy: "Energia"
    readonly property string noBattery: "Brak baterii"
    readonly property string media: "Multimedia"
    readonly property string calendar: "Kalendarz"
    readonly property string notifications: "Powiadomienia"
    readonly property string applications: "Aplikacje"
    readonly property string files: "Pliki"
    readonly property string launchApplication: "Uruchom aplikację"
    readonly property string searchApplicationsFilesClipboard: "Aplikacje, pliki, schowek..."
    readonly property string searchingFiles: "Wyszukiwanie plików…"
    readonly property string closeWindow: "Zamknij okno"
    readonly property string moveToWorkspace: "Przenieś do workspace"
    readonly property string noActiveWindow: "Brak aktywnego okna"
    readonly property string desktop: "Pulpit"
    readonly property string window: "Okno"
    readonly property string zenBrowser: "Zen Browser"
    readonly property string jellyfin: "Jellyfin"
    readonly property string clipboardPaused: "Historia schowka wstrzymana"
    readonly property string resume: "Wznów"
    readonly property string pause: "Pauza"
    readonly property string clipboardEmpty: "Historia jest pusta"
    readonly property string clearEverything: "Wyczyść wszystko"
    readonly property string output: "Wyjście"
    readonly property string input: "Wejście"
    readonly property string network: "Sieć"
    readonly property string noConnection: "Brak połączenia"
    readonly property string ethernet: "Ethernet"
    readonly property string ethernetConnected: "Ethernet jest połączony"
    readonly property string availableNetworks: "Dostępne sieci"
    readonly property string wifiDisabled: "Wi‑Fi jest wyłączone"
    readonly property string noNetworks: "Nie znaleziono sieci"
    readonly property string connected: "Połączono"
    readonly property string connecting: "Łączenie…"
    readonly property string remembered: "Zapamiętana"
    readonly property string wpaPassword: "Hasło WPA"
    readonly property string connect: "Połącz"
    readonly property string advanced: "Zaawansowane"
    readonly property string networkSettings: "Ustawienia sieci"
    readonly property string networkWifiHint: "Połączenia bezprzewodowe i zapisane sieci"
    readonly property string networkVpn: "VPN"
    readonly property string networkVpnHint: "Prywatne połączenia z siecią"
    readonly property string networkVpnSearch: "Szukaj połączenia VPN…"
    readonly property string networkNearby: "Dostępne"
    readonly property string networkAddVpn: "Dodaj VPN"
    readonly property string networkRemoveVpn: "Usuń VPN"
    readonly property string networkNoVpn: "Brak połączeń VPN"
    readonly property string networkNoVpnHint: "Dodaj konfigurację otrzymaną od dostawcy VPN lub administratora sieci."
    readonly property string networkVpnImportHint: "Wybierz plik konfiguracji. Po dodaniu profil pojawi się na liście — połączysz się z nim osobnym przyciskiem."
    readonly property string networkVpnType: "Typ połączenia"
    readonly property string networkVpnFile: "Wybierz plik…"
    readonly property string networkVpnFileTitle: "Konfiguracja VPN"
    readonly property string networkVpnAdd: "Dodaj połączenie"
    readonly property string networkVpnFileError: "Nie można odczytać tego pliku. Wybierz lokalną konfigurację VPN o rozmiarze do 1 MB."
    readonly property string networkVpnConfigError: "Nie udało się odczytać konfiguracji. Sprawdź typ VPN i zawartość pliku."
    readonly property string networkVpnUnsupported: "Konfiguracja zawiera nieobsługiwane opcje. Dla WireGuard użyj pliku bez skryptów PreUp/PostUp/PreDown/PostDown, SaveConfig i własnych tabel routingu."
    readonly property string networkVpnPluginMissing: "OpenVPN wymaga zainstalowanej wtyczki networkmanager-openvpn."
    readonly property string networkVpnConnectionFailed: "Połączenie VPN zostało przerwane. Sprawdź konfigurację i dostęp do sieci."
    readonly property string networkNotConnected: "Niepołączono"
    readonly property string networkDisconnecting: "Rozłączanie…"
    readonly property string networkDisconnect: "Rozłącz"
    readonly property string networkOverview: "Wróć do listy"
    readonly property string networkDiscardTitle: "Masz niezapisane zmiany."
    readonly property string networkDiscardHint: "Zachowaj edycję albo odrzuć zmiany, aby kontynuować."
    readonly property string networkDiscard: "Odrzuć zmiany"
    readonly property string networkKeepEditing: "Kontynuuj edycję"
    readonly property string networkConnectionSettings: "Ustawienia połączenia"
    readonly property string networkSelectedFile: "Wybrany plik: %1"
    readonly property string networkRetry: "Spróbuj ponownie"
    readonly property string networkWireguardFilter: "WireGuard (*.conf)"
    readonly property string networkOpenvpnFilter: "OpenVPN (*.ovpn *.conf)"
    readonly property string networkBack: "Wróć do sieci"
    readonly property string networkSaved: "Zapisane sieci"
    readonly property string networkNoSaved: "Brak zapisanych sieci"
    readonly property string networkSearch: "Szukaj zapisanej sieci…"
    readonly property string networkProfileName: "Nazwa połączenia"
    readonly property string networkGeneral: "Ogólne"
    readonly property string networkAutoConnect: "Łącz automatycznie"
    readonly property string networkHidden: "Sieć ukryta"
    readonly property string networkMetered: "Połączenie taryfowe"
    readonly property string networkAutomatic: "Automatycznie"
    readonly property string networkYes: "Tak"
    readonly property string networkNo: "Nie"
    readonly property string networkIpMethod: "Konfiguracja adresu"
    readonly property string networkDhcp: "Automatycznie (DHCP)"
    readonly property string networkManual: "Ręcznie"
    readonly property string networkLinkLocal: "Tylko łącze lokalne"
    readonly property string networkIpDisabled: "Wyłączona"
    readonly property string networkKeepMethod: "Bieżąca: %1"
    readonly property string networkAddresses: "Adresy IP z prefiksem"
    readonly property string networkGateway: "Brama"
    readonly property string networkAutoDns: "DNS z sieci"
    readonly property string networkDns: "Własne serwery DNS"
    readonly property string networkDnsHint: "Kilka adresów oddziel przecinkami."
    readonly property string networkAddress4Hint: "np. 192.168.1.20/24"
    readonly property string networkAddress6Hint: "np. 2001:db8::20/64"
    readonly property string networkSave: "Zapisz zmiany"
    readonly property string networkNextConnection: "Zmiany zostaną użyte przy następnym połączeniu."
    readonly property string networkForget: "Zapomnij sieć"
    readonly property string networkForgetHint: "Usunąć zapisane połączenie „%1”? Następne połączenie może wymagać ponownego podania hasła."
    readonly property string networkLoading: "Wczytywanie ustawień…"
    readonly property string networkSaving: "Zapisywanie…"
    readonly property string networkForgetting: "Usuwanie profilu…"
    readonly property string networkInvalidName: "Wpisz nazwę połączenia (1–128 znaków)."
    readonly property string networkInvalidAddress: "Podaj poprawne adresy z prefiksem dla wybranego IP, np. 192.168.1.20/24."
    readonly property string networkInvalidGateway: "Podaj poprawny adres bramy dla wybranej wersji IP."
    readonly property string networkInvalidDns: "Podaj poprawne adresy serwerów DNS dla wybranej wersji IP."
    readonly property string networkSettingsConflict: "Te ustawienia zostały zmienione w innym miejscu. Wróć do listy i otwórz profil ponownie."
    readonly property string networkPermissionDenied: "Brak uprawnień do zmiany tego połączenia."
    readonly property string networkSettingsTimeout: "NetworkManager nie potwierdził operacji w wymaganym czasie. Otwórz profil ponownie, aby sprawdzić jego stan."
    readonly property string networkProfileUnavailable: "Ten profil sieci jest już niedostępny."
    readonly property string networkSettingsFailed: "Nie udało się zmienić ustawień sieci. Sprawdź wpisane wartości i spróbuj ponownie."
    readonly property string invalidWpaPassword: "Hasło WPA musi mieć 8–63 znaki albo 64 cyfry szesnastkowe."
    readonly property string advancedNetworkRequired: "Ten typ zabezpieczeń wymaga wcześniej skonfigurowanego profilu sieci."
    readonly property string networkConnectionFailed: "Nie udało się połączyć z siecią."
    readonly property string enabled: "Włączony"
    readonly property string disabled: "Wyłączony"
    readonly property string bluetoothEnabled: "Bluetooth włączony"
    readonly property string bluetoothDisabled: "Bluetooth wyłączony"
    readonly property string bluetoothUnavailable: "Bluetooth jest wyłączony"
    readonly property string savedDevices: "Zapamiętane urządzenia"
    readonly property string disconnected: "Rozłączono"
    readonly property string noSavedDevices: "Brak zapamiętanych urządzeń"
    readonly property string pairNewDevice: "Sparuj nowe urządzenie"
    readonly property string bluetoothHideDevices: "Ukryj dostępne urządzenia"
    readonly property string bluetoothSearching: "Wyszukiwanie urządzeń…"
    readonly property string bluetoothNearby: "Dostępne urządzenia"
    readonly property string bluetoothNearbyCount: "Dostępne urządzenia (%1)"
    readonly property string bluetoothUnnamed: "Urządzenie bez nazwy"
    readonly property string bluetoothPickerHint: "Wybierz urządzenie, aby je sparować."
    readonly property string bluetoothNoNearby: "Brak nowych urządzeń"
    readonly property string bluetoothDiscoveryHint: "Włącz tryb parowania na urządzeniu."
    readonly property string bluetoothPair: "Sparuj"
    readonly property string bluetoothPairing: "Parowanie…"
    readonly property string bluetoothPin: "PIN urządzenia"
    readonly property string bluetoothPasskey: "Kod (1–6 cyfr)"
    readonly property string bluetoothPinHint: "Wpisz PIN podany na urządzeniu lub w jego instrukcji."
    readonly property string bluetoothPasskeyHint: "Wpisz kod wyświetlony na urządzeniu."
    readonly property string bluetoothConfirmHint: "Sprawdź, czy oba urządzenia pokazują ten sam kod."
    readonly property string bluetoothDisplayHint: "Wpisz ten kod na parowanej klawiaturze i naciśnij Enter."
    readonly property string bluetoothAuthorizeHint: "Zezwolić temu urządzeniu na parowanie i połączenie?"
    readonly property string bluetoothCodesMatch: "Kod się zgadza"
    readonly property string bluetoothEntered: "Wpisano %1 z 6 cyfr"
    readonly property string bluetoothPairElsewhere: "Parowanie trwa na drugim monitorze."
    readonly property string bluetoothBlocked: "Adapter Bluetooth jest zablokowany."
    readonly property string bluetoothPairTimeout: "Upłynął czas parowania. Włącz tryb parowania na urządzeniu i spróbuj ponownie."
    readonly property string bluetoothPairRejected: "Parowanie zostało odrzucone lub anulowane na urządzeniu."
    readonly property string bluetoothPairAuthFailed: "Niepoprawny PIN lub kod. Spróbuj sparować urządzenie ponownie."
    readonly property string bluetoothPairDenied: "Brak uprawnień do parowania Bluetooth."
    readonly property string bluetoothPairInProgress: "Urządzenie jest już sparowane lub trwa inne parowanie."
    readonly property string bluetoothPairUnavailable: "Urządzenie lub usługa Bluetooth są niedostępne."
    readonly property string bluetoothPairFailed: "Nie udało się sparować. Włącz tryb parowania na urządzeniu i spróbuj ponownie."
    readonly property string bluetoothTrustFailed: "Sparowano, ale nie udało się zapamiętać zaufania do urządzenia."
    readonly property string bluetoothConnectFailed: "Sparowano. Nie udało się połączyć — wybierz urządzenie z listy, aby ponowić połączenie."
    readonly property string bluetoothAdapter: "Adapter Bluetooth"
    readonly property string bluetoothDeviceSettings: "Ustawienia urządzenia %1"
    readonly property string bluetoothDeviceName: "Nazwa urządzenia"
    readonly property string bluetoothRename: "Zmień nazwę"
    readonly property string bluetoothSaveName: "Zapisz nazwę"
    readonly property string bluetoothDefaultName: "Przywróć nazwę urządzenia"
    readonly property string bluetoothForget: "Zapomnij urządzenie"
    readonly property string bluetoothForgetHint: "Usunąć parowanie z „%1”? Urządzenie zostanie rozłączone. Aby połączyć je ponownie, trzeba będzie je sparować."
    readonly property string bluetoothBack: "Wróć do urządzeń"
    readonly property string bluetoothWorking: "Zapisywanie…"
    readonly property string bluetoothForgetting: "Usuwanie parowania…"
    readonly property string bluetoothDisconnecting: "Rozłączanie…"
    readonly property string bluetoothRenamed: "Nazwa urządzenia została zapisana."
    readonly property string bluetoothActionDenied: "Brak uprawnień do zmiany urządzenia Bluetooth."
    readonly property string bluetoothRenameFailed: "Nie udało się zapisać nazwy. Spróbuj ponownie."
    readonly property string bluetoothForgetFailed: "Nie udało się usunąć parowania. Spróbuj ponownie."
    readonly property string bluetoothConnectionFailed: "Nie udało się połączyć. Włącz urządzenie i upewnij się, że jest w zasięgu."
    readonly property string bluetoothDisconnectFailed: "Nie udało się rozłączyć urządzenia. Spróbuj ponownie."
    readonly property string powerProfile: "Profil zasilania"
    readonly property string profileSaver: "Oszczędny"
    readonly property string profileBalanced: "Zrównoważony"
    readonly property string profilePerformance: "Wydajność"
    readonly property string performanceUnavailable: "Profil wydajności nie jest dostępny na tym urządzeniu."
    readonly property string calculating: "Obliczanie…"
    readonly property string remaining: "Pozostało"
    readonly property string untilFull: "Do pełna"
    readonly property string charged: "Naładowana"
    readonly property string profile: "Profil"
    readonly property string health: "Kondycja"
    readonly property string nothingPlaying: "Brak aktywnych multimediów"
    readonly property string unknownMedia: "Multimedia bez tytułu"
    readonly property string mediaAutomatic: "Automatycznie"
    readonly property string mediaPrevious: "Poprzednie multimedia"
    readonly property string mediaNext: "Następne multimedia"
    readonly property string mediaPlay: "Odtwórz"
    readonly property string mediaPause: "Wstrzymaj"
    readonly property string player: "Odtwarzacz"
    readonly property string trayOverflow: "Pozostałe ikony"
    readonly property string trayEmpty: "Brak dodatkowych ikon"
    readonly property string moreTrayIcons: "Więcej ikon zasobnika"

    readonly property string notificationsDnd: "Nie przeszkadzać"
    readonly property string notificationsEmpty: "Brak powiadomień"
    readonly property string notificationsDiscard: "Odrzuć"
    readonly property string notificationsUndo: "Cofnij"
    readonly property string notificationsDiscarded: "Powiadomienie odrzucone"
    readonly property string notificationsClear: "Wyczyść historię"
    readonly property string notificationsClearAction: "Wyczyść powiadomienia"
    readonly property string notificationsClearConfirm: "Usunąć całą historię powiadomień?"
    readonly property string notificationsSearch: "Szukaj w powiadomieniach…"
    readonly property string notificationsOlder: "Starsze"
    readonly property string notificationsLess: "Zwiń"
    readonly property string notificationsUnknownApp: "Nieznana aplikacja"
    readonly property string notificationsCannotActivate: "Nie znaleziono okna ani aplikacji dla tego powiadomienia."
    readonly property string notificationsExpand: "Rozwiń powiadomienie"
    readonly property string notificationsCollapse: "Zwiń powiadomienie"
    readonly property string notificationsOpen: "Otwórz powiadomienie"
    readonly property string notificationsOpenApp: "Otwórz"
    readonly property string notificationsReply: "Odpowiedz"
    readonly property string notificationsReplyPlaceholder: "Napisz odpowiedź…"
    readonly property string notificationsReplySend: "Wyślij"
    readonly property string notificationsReplyUnavailable: "Nie można już odpowiedzieć na to powiadomienie."

    function screenshotPixels(width, height) {
        return width + " × " + height + " px";
    }

    function connectedDevices(count) {
        return "Połączone urządzenia: " + count;
    }

    function confirmAction(label) {
        return "Potwierdź: " + label.toLocaleLowerCase() + "?";
    }

    function passwordFor(name) {
        return "Hasło do „" + name + "”";
    }

    function authenticationText(value) {
        // Translate only complete, known PAM lines. Preserve custom prompts,
        // device/key names and the lockout duration supplied by the backend.
        return String(value || "").split("\n").map(line => {
            const text = line.trim();
            if (/^Password:?$/i.test(text))
                return authPassword;
            const unlock = /^\((\d+) minutes?(?: left)? to unlock\)$/i.exec(text);
            if (unlock)
                return authUnlockIn.arg(unlock[1]);
            return line;
        }).join("\n");
    }
    readonly property string greeterSelectUser: "Wybierz użytkownika"
    readonly property string greeterUnavailable: "Logowanie jest niedostępne."
    readonly property string greeterNoUsers: "Brak użytkowników do zalogowania."
    readonly property string greeterFailed: "Uwierzytelnianie nie powiodło się."
    readonly property string greeterRetryFingerprint: "Ponów odczyt palca"
    readonly property string greeterFingerprintError: "błąd czytnika"
}
